from __future__ import annotations

import argparse
import json
import os
import platform
import shutil
import statistics
import subprocess
import sys
import time
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "benchmarks.json"
RESULTS_DIR = ROOT / "results"
REPORT = ROOT / "report.md"


@dataclass(frozen=True)
class CommandSpec:
    language: str
    display: str
    benchmark_id: str
    source: Path
    command: list[str]
    compile_command: list[str] | None = None
    binary: Path | None = None


def load_config() -> dict[str, Any]:
    with CONFIG.open("r", encoding="utf-8") as fh:
        return json.load(fh)


def executable_exists(name: str) -> bool:
    return shutil.which(name) is not None


def run_checked(command: list[str], cwd: Path = ROOT) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        command,
        cwd=str(cwd),
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )


def prepare_command(language_id: str, language_cfg: dict[str, Any], benchmark: dict[str, Any]) -> tuple[CommandSpec | None, str | None]:
    source = ROOT / language_cfg["source_dir"] / f"{benchmark['id']}{language_cfg['extension']}"
    if not source.exists():
        return None, f"missing source: {source.relative_to(ROOT)}"

    display = language_cfg["display"]
    if language_id == "python":
        runner = language_cfg.get("runner", "python3")
        if not executable_exists(runner):
            return None, f"missing executable: {runner}"
        return CommandSpec(language_id, display, benchmark["id"], source, [runner, str(source)]), None

    compiler = language_cfg["compiler"]
    if not executable_exists(compiler):
        return None, f"missing compiler: {compiler}"

    binary_dir = ROOT / language_cfg["binary_dir"]
    binary_dir.mkdir(parents=True, exist_ok=True)
    binary = binary_dir / benchmark["id"]
    compile_command = [compiler, *language_cfg.get("compile_args", []), str(source), "-o", str(binary)]
    compiled = run_checked(compile_command)
    if compiled.returncode != 0:
        reason = compiled.stderr.strip() or compiled.stdout.strip() or "compile failed"
        return None, reason
    return CommandSpec(language_id, display, benchmark["id"], source, [str(binary)], compile_command, binary), None


def measure(command: list[str], size: int, repeat: int, warmup: int, timeout: float) -> dict[str, Any]:
    full_command = [*command, str(size)]
    for _ in range(warmup):
        completed = subprocess.run(full_command, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=timeout, check=False)
        if completed.returncode != 0:
            raise RuntimeError(completed.stderr.strip() or completed.stdout.strip() or "warmup failed")

    samples: list[float] = []
    checksum = ""
    for _ in range(repeat):
        started = time.perf_counter_ns()
        completed = subprocess.run(full_command, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=timeout, check=False)
        elapsed = (time.perf_counter_ns() - started) / 1_000_000_000
        if completed.returncode != 0:
            raise RuntimeError(completed.stderr.strip() or completed.stdout.strip() or "benchmark failed")
        samples.append(elapsed)
        checksum = completed.stdout.strip().splitlines()[-1] if completed.stdout.strip() else ""

    return {
        "samples_sec": samples,
        "min_sec": min(samples),
        "median_sec": statistics.median(samples),
        "mean_sec": statistics.fmean(samples),
        "stdev_sec": statistics.stdev(samples) if len(samples) > 1 else 0.0,
        "checksum": checksum,
    }


def environment() -> dict[str, str]:
    def version(command: list[str]) -> str:
        if not executable_exists(command[0]):
            return "not found"
        completed = run_checked(command)
        output = (completed.stdout or completed.stderr).strip().splitlines()
        return output[0] if output else "unknown"

    return {
        "timestamp_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "platform": platform.platform(),
        "processor": platform.processor() or "unknown",
        "python": sys.version.split()[0],
        "g++": version(["g++", "--version"]),
        "cjc": version(["cjc", "--version"]),
    }


def render_report(payload: dict[str, Any]) -> str:
    lines = [
        "# Cangjie / Python / C++ Performance Report",
        "",
        "Generated by `python3 perf/run.py`.",
        "",
        "## Environment",
        "",
        "| Key | Value |",
        "| --- | --- |",
    ]
    for key, value in payload["environment"].items():
        lines.append(f"| {key} | {value} |")

    lines.extend(["", "## Results", ""])
    by_benchmark: dict[str, list[dict[str, Any]]] = {}
    for item in payload["results"]:
        by_benchmark.setdefault(item["benchmark_id"], []).append(item)

    benchmark_meta = {b["id"]: b for b in payload["benchmarks"]}
    for benchmark_id, rows in by_benchmark.items():
        meta = benchmark_meta[benchmark_id]
        successful = [row for row in rows if row["status"] == "ok"]
        baseline = next((row for row in successful if row["language"] == "cangjie"), None)
        if baseline is None and successful:
            baseline = min(successful, key=lambda row: row["measurement"]["median_sec"])
        baseline_time = baseline["measurement"]["median_sec"] if baseline else None
        baseline_name = baseline["display"] if baseline else "n/a"

        lines.extend([
            f"### {meta['name']} (`{benchmark_id}`)",
            "",
            meta["description"],
            "",
            f"Input size: `{meta['effective_size']}`. Ratio baseline: **{baseline_name}**.",
            "",
            "| Language | Status | Median (s) | Mean (s) | Min (s) | Stdev (s) | Ratio | Checksum / Note |",
            "| --- | --- | ---: | ---: | ---: | ---: | ---: | --- |",
        ])
        for row in sorted(rows, key=lambda r: (r["status"] != "ok", r["display"])):
            if row["status"] == "ok":
                m = row["measurement"]
                ratio = m["median_sec"] / baseline_time if baseline_time else 0.0
                lines.append(
                    f"| {row['display']} | ok | {m['median_sec']:.6f} | {m['mean_sec']:.6f} | "
                    f"{m['min_sec']:.6f} | {m['stdev_sec']:.6f} | {ratio:.2f}x | `{m['checksum']}` |"
                )
            else:
                note = str(row.get("reason", "skipped")).replace("\n", "<br>")
                lines.append(f"| {row['display']} | {row['status']} | - | - | - | - | - | {note} |")
        lines.append("")

    lines.extend([
        "## Methodology",
        "",
        "- Each benchmark is implemented separately for Cangjie, Python, and C++ with the same input-size argument and checksum output contract.",
        "- The runner measures wall-clock process execution time with `time.perf_counter_ns()` and reports min/median/mean/stdev over repeated runs.",
        "- C++ is compiled with optimized flags from `perf/benchmarks.json`; Cangjie is compiled with `cjc` when the toolchain is available.",
        "- Missing toolchains are reported as skipped instead of failing the whole suite, so the same command works on partial environments.",
        "",
    ])
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Run Cangjie/Python/C++ performance benchmarks and generate perf/report.md")
    parser.add_argument("--quick", action="store_true", help="use smaller input sizes for smoke testing")
    parser.add_argument("--repeat", type=int, default=5, help="measured repetitions per benchmark")
    parser.add_argument("--warmup", type=int, default=1, help="warmup repetitions per benchmark")
    parser.add_argument("--timeout", type=float, default=120.0, help="per-process timeout in seconds")
    parser.add_argument("--languages", default="python,cpp,cangjie", help="comma-separated language ids")
    parser.add_argument("--benchmarks", default="", help="comma-separated benchmark ids; defaults to all")
    args = parser.parse_args(argv)

    config = load_config()
    requested_languages = [item.strip() for item in args.languages.split(",") if item.strip()]
    requested_benchmarks = {item.strip() for item in args.benchmarks.split(",") if item.strip()}

    results: list[dict[str, Any]] = []
    benchmarks = []
    for benchmark in config["benchmarks"]:
        if requested_benchmarks and benchmark["id"] not in requested_benchmarks:
            continue
        effective = int(benchmark["quick_size"] if args.quick else benchmark["size"])
        meta = dict(benchmark)
        meta["effective_size"] = effective
        benchmarks.append(meta)
        for language_id in requested_languages:
            language_cfg = config["languages"].get(language_id)
            if language_cfg is None:
                results.append({"benchmark_id": benchmark["id"], "language": language_id, "display": language_id, "status": "skipped", "reason": "unknown language"})
                continue
            command, reason = prepare_command(language_id, language_cfg, benchmark)
            if command is None:
                results.append({"benchmark_id": benchmark["id"], "language": language_id, "display": language_cfg["display"], "status": "skipped", "reason": reason})
                continue
            try:
                measurement = measure(command.command, effective, args.repeat, args.warmup, args.timeout)
                results.append({"benchmark_id": benchmark["id"], "language": language_id, "display": command.display, "status": "ok", "measurement": measurement})
            except Exception as exc:  # noqa: BLE001 - report benchmark failures without aborting the suite
                results.append({"benchmark_id": benchmark["id"], "language": language_id, "display": command.display, "status": "failed", "reason": str(exc)})

    payload = {"environment": environment(), "benchmarks": benchmarks, "results": results}
    RESULTS_DIR.mkdir(exist_ok=True)
    result_path = RESULTS_DIR / f"results-{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}.json"
    result_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    REPORT.write_text(render_report(payload), encoding="utf-8")
    print(f"Wrote {REPORT.relative_to(ROOT)}")
    print(f"Wrote {result_path.relative_to(ROOT)}")
    return 0
